package fold

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ubixsys/ubixshepherd/internal/store"
)

// The generated view sits between these markers in a repo's coordination file. Shepherd
// rewrites only what is between them, so the rest (a log sessions append to by hand)
// stays theirs.
const (
	viewBegin = "<!-- shepherd:begin. Generated by uBixShepherd from its lanes; edits between these markers are overwritten. -->"
	viewEnd   = "<!-- shepherd:end -->"
)

// RenderView is the Markdown block for a repo's live lanes and tag reservations.
func (f *Fold) RenderView(ctx context.Context, repo store.Repo) (string, error) {
	lanes, err := f.Store.Lanes(ctx, repo.ID)
	if err != nil {
		return "", err
	}
	tags, err := f.Store.Reservations(ctx, repo.ID)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(viewBegin + "\n\n")
	b.WriteString("## Live lanes (uBixShepherd)\n\n")
	b.WriteString("Kept by Shepherd; sessions on Shepherd use `shepherd lane open` instead of adding rows by hand. A lane's scope is held: another lane's push into it is refused.\n\n")
	if len(lanes) == 0 {
		b.WriteString("No open lanes.\n")
	} else {
		b.WriteString("| Lane | Branch | Agent | Scope | Since |\n| ---- | ------ | ----- | ----- | ----- |\n")
		for _, l := range lanes {
			// No run yet: say what opened the lane, not a guess at who.
			agent := "via " + l.Origin.Surface()
			if l.Origin.Agent != "" {
				agent = l.Origin.Agent + " " + agent
			}
			if runs, err := f.Store.Runs(ctx, l.ID, "", 1); err == nil && len(runs) > 0 {
				agent = runs[0].Agent
				if runs[0].State == store.RunRunning {
					agent += " (running)"
				}
			}
			var sc []string
			for _, g := range l.Scope {
				sc = append(sc, "`"+g+"`")
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s |\n", l.Name, l.Branch, agent, strings.Join(sc, ", "), l.Created.Local().Format("2006-01-02"))
		}
	}
	if len(tags) > 0 {
		b.WriteString("\n**Tags reserved:** ")
		var ts []string
		for _, r := range tags {
			who := "no lane"
			if l, err := f.Store.Lane(ctx, r.LaneID); err == nil {
				who = l.Name
			}
			ts = append(ts, fmt.Sprintf("`%s` (%s, %s)", r.Tag, who, r.State))
		}
		b.WriteString(strings.Join(ts, ", ") + ". Reserve the next one with `shepherd tag reserve`; never pick a number by hand.\n")
	}
	fmt.Fprintf(&b, "\n_Updated %s._\n\n%s", time.Now().Format("2006-01-02 15:04"), viewEnd)
	return b.String(), nil
}

// WriteView puts the generated view into the repo's coordination file, between the
// markers, or after the file's title when there are none yet. It does nothing for a repo
// whose profile names no coordination file.
func (f *Fold) WriteView(ctx context.Context, repoID int64) error {
	repo, err := f.Store.Repo(ctx, repoID)
	if err != nil {
		return err
	}
	file := f.Conf().Profile(repo.Name).CoordFile
	if file == "" {
		return nil
	}
	if !filepath.IsAbs(file) {
		file = filepath.Join(repo.Path, file)
	}
	view, err := f.RenderView(ctx, repo)
	if err != nil {
		return err
	}
	old, err := os.ReadFile(file)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return writeAtomic(file, []byte(InsertView(string(old), view)))
}

// InsertView replaces the block between the markers, or inserts it after the first
// heading (or at the top) when the markers are not there yet.
func InsertView(doc, view string) string {
	if i := strings.Index(doc, viewBegin); i >= 0 {
		if j := strings.Index(doc[i:], viewEnd); j >= 0 {
			return doc[:i] + view + doc[i+j+len(viewEnd):]
		}
	}
	if strings.HasPrefix(doc, "# ") {
		nl := strings.Index(doc, "\n")
		if nl < 0 {
			return doc + "\n\n" + view + "\n"
		}
		return doc[:nl+1] + "\n" + view + "\n" + doc[nl+1:]
	}
	return view + "\n\n" + doc
}

func writeAtomic(path string, b []byte) error {
	mode := os.FileMode(0o644)
	if fi, err := os.Stat(path); err == nil {
		mode = fi.Mode().Perm()
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".shepherd-view-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(b); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	os.Chmod(tmp.Name(), mode)
	return os.Rename(tmp.Name(), path)
}
